'use strict';
/* Starter threads written in casual forum style. Each thread: [forum, prefix, title, opening post, [replies]].
   Authors are assigned from the starter member pool when the content is added. */
module.exports = [
  ['f-skin', 'guide', 'my 3 step routine that finally cleared my skin', 'ok so after literally years of 10 step routines this is what actually worked:\n\n[b]AM:[/b] gentle cleanser, moisturiser, spf 50\n[b]PM:[/b] cleanser, adapalene 3x a week, moisturiser\n\nthe biggest thing was being consistent and NOT switching stuff every 2 weeks. give anything new 6-8 weeks before you judge it', [
    'saving this 🙏', 'which moisturiser do u use?', 'cerave pm lotion, nothing fancy lol', 'this is so true about switching products, i do that constantly 😭', 'did u purge on the adapalene?', 'yeah for like 3 weeks it was rough but it calmed down', 'starting this tonight wish me luck', 'the consistency thing is so real, my skin got better when i got lazier lmao']],
  ['f-skin', 'question', 'does double cleansing actually matter??', 'i see it everywhere but i barely wear makeup. is it worth it or is it just tiktok hype', [
    'only on days u wear spf or makeup imo', 'i do it every night but thats bc i wear sunscreen daily', 'oil cleanser changed my life ngl, my pores look way smaller', 'if ur skin is dry it can be too much tbh', 'this ^ i got super tight skin from it', 'micellar water first then cleanser works too if u dont want oil', 'thanks guys ill just do it on spf days then']],
  ['f-skin', 'discussion', 'unpopular opinion: you dont need vitamin c', 'everyone acts like its essential but spf does way more for preventing dark spots. vit c is a nice extra not a must', [
    'finally someone said it', 'agree, spf > everything', 'tbf vit c did help my post acne marks a bit', 'mine just oxidised and turned orange lol waste of money', 'the cheap ones are basically useless tho, formulation matters', 'niacinamide did more for me than vit c ever did', 'spf gang 🫡']],
  ['f-skin', 'question', 'what spf doesnt leave a white cast??', 'every sunscreen i try makes me look grey. i have medium-deep skin. help', [
    'beauty of joseon is literally the only one that works for me', 'any chemical sunscreen should be fine, mineral ones are the white cast ones', 'black girl sunscreen is literally made for this', 'la roche posay anthelios invisible fluid is good too', 'avoid anything with zinc oxide high up the list', 'ty!! gonna try beauty of joseon first', 'update us!']],
  ['f-skin', 'success', '6 months of retinol before/after (no pics but trust)', 'started at 0.25% twice a week, now 0.5% every other night. my texture is SO much smoother and my old acne marks are way lighter. slow and steady is everything', [
    'love this congrats!!', 'how bad was the purge', 'honestly mild, i buffered with moisturiser first', 'buffering is underrated', 'did u use it around ur eyes?', 'nope, i skipped under eyes for the first few months', 'this is motivating i keep quitting after 2 weeks 😭', 'dont quit!! the first month is the worst']],
  ['f-skin', 'question', 'is it normal for my skin to be oily AND dry??', 'my t zone is shiny by lunch but my cheeks are flaky. what am i supposed to do lol', [
    'combination skin bestie welcome', 'probably dehydrated, try a lighter gel moisturiser', 'hyaluronic acid on damp skin helped me', 'stop using harsh foaming cleansers if u are', 'omg i do use a foaming one', 'there it is lol', 'switch to a cream cleanser and see in 2 weeks']],
  ['f-hair', 'guide', 'wash day routine for 4c hair', 'pre poo with oil > sulfate free shampoo > deep condition 30 mins with heat > leave in > seal with oil > protective style\n\nthe deep condition is the one step i never skip', [
    'how often do u wash?', 'every 7-10 days usually', 'what deep conditioner??', 'shea moisture manuka honey one, its pricey but lasts', 'the heat cap makes such a difference', 'adding the pre poo step, never tried it', 'this is basically my routine too, 4c hair is a commitment lol', 'protective styles saved my length fr']],
  ['f-hair', 'success', 'growing out over plucked brows: 4 month update', 'stopped tweezing completely, brushed them up every day and let them grow wild for 4 months. theyre finally filling in!!! patience is literally everything', [
    'this gives me hope', 'did u use any serum?', 'just castor oil at night, not sure if it did anything tbh', 'the awkward phase is the worst part congrats for getting through it', 'mine have been growing for 2 months and i want to pluck SO bad', 'DONT do it lol', 'brow lamination might help u through the awkward phase']],
  ['f-hair', 'question', 'how do i stop my hair being so frizzy', 'wavy hair, frizzes the second i step outside. ive tried everything', [
    'stop brushing it dry', 'microfibre towel instead of normal towel', 'silk pillowcase helped me a lot', 'gel while its soaking wet then scrunch out the crunch', 'curly girl method maybe? worked for my 2c waves', 'avoid sulfates and drying alcohols', 'omg i do brush it dry every morning', 'thats probably like 80% of it lol']],
  ['f-hair', 'discussion', 'curtain bangs: worth it or regret?', 'thinking about getting curtain bangs but im scared ill hate them', [
    'worth it if u style them every day', 'i regretted mine, my cowlick ruined them', 'they grow out pretty easy at least', 'they suit almost every face shape tbh', 'get them longer than u think, they shrink', 'do it!! post a pic after', 'mine looked great for 3 weeks then i got lazy lol']],
  ['f-hair', 'question', 'lash serums: do they actually work', 'thinking of trying one but heard mixed things', [
    'the prescription one worked for me but it darkened my eyelid a bit', 'some can change eye colour slightly so read the label', 'castor oil did nothing for me', 'honestly just a good lash lift is less risky', 'a lift + tint is what i do every 6 weeks', 'good to know, might just do a lift then']],
  ['f-makeup', 'question', 'beginner: what 5 products do i actually need', 'overwhelmed by literally everything. if you had to start with 5 what would they be', [
    'skin tint, concealer, brow gel, mascara, cream blush', 'this ^ covers 90% of looks', 'id swap skin tint for just concealer where u need it', 'tinted lip balm too', 'dont start with foundation, its so hard to match', 'cream blush is so beginner friendly', 'thank u all this is so helpful 💕', 'post ur first look!!']],
  ['f-makeup', 'guide', 'how i found my colour season and why it changed everything', 'daylight, no makeup, hair back. hold gold vs silver fabric under your face and see which makes your skin look clearer. im a soft summer (muted cool). swapping warm bronzer for a cool rose blush was a GAME CHANGER', [
    'soft summer twins!! dusty pinks forever', 'doing this tomorrow morning', 'i keep getting different results depending on the light lol', 'has to be natural daylight by a window, no lamps', 'how do u tell warm vs cool if ur neutral', 'vein test never works for me', 'the drape method is way more accurate than the vein thing', 'this explains why bronzer always looked muddy on me']],
  ['f-makeup', 'discussion', 'underrated drugstore products?', 'drop ur holy grail cheap makeup', [
    'maybelline sky high mascara', 'elf putty primer', 'nyx butter gloss always', 'essence lash princess is better than most expensive ones', 'wet n wild brow pencil', 'rimmel stay matte powder', 'elf camo concealer lasts all day on me', 'adding all of these to my cart lol']],
  ['f-makeup', 'question', 'how do u make concealer not crease', 'every time it settles into my undereyes within an hour', [
    'less product!! seriously use way less', 'set with a tiny bit of powder', 'moisturise first or itll cling to dry patches', 'tap it in with ur ring finger instead of a sponge', 'thinner concealers crease less imo', 'i was using like 3 layers 💀', 'yeah thats it lol']],
  ['f-makeup', 'success', 'finally learned winged liner after 2 years', 'the trick for me was drawing the wing first as a line from the lower lash line, then connecting it. took forever but i can do both sides even now', [
    'both sides even is the real achievement', 'tape method helped me in the beginning', 'im still at the uneven stage lol', 'gel liner was easier for me than liquid', 'proud of u fr', 'teach me']],
  ['f-fitness', 'discussion', 'pilates vs weights for a toned look?', 'ive done both. lifting changed my shape the most but pilates fixed my posture and core. doing both is ideal if u have time', [
    'pilates fixed my lower back pain so its staying', 'lifting heavy wont make u bulky btw, its a myth', 'reformer pilates is so expensive tho 😭', 'mat pilates at home is free!', 'eat enough protein or neither will show results', 'i do 3 days lifting 2 days pilates', 'that sounds like a great split', 'glute days are my favourite lol']],
  ['f-fitness', 'success', 'posture check: 30 days of wall angels and chin tucks', '10 mins every morning for a month. my shoulders sit so much further back and my neck looks longer in pics', [
    'love this', 'rows at the gym helped me too', 'can u explain wall angels', 'back flat against the wall, arms like a goalpost, slide them up and down keeping contact', 'doing this tomorrow', 'my phone posture is so bad i need this', 'same 😭']],
  ['f-fitness', 'question', 'how do i actually start going to the gym', 'gym anxiety is real. i dont know what to do once im there', [
    'go with a plan written on ur phone', 'start with machines, theyre less intimidating', 'go at quiet times like early morning', 'nobody is looking at u i promise', 'headphones in and pretend u know what ur doing lol', 'a beginner full body routine 3x a week is perfect', 'thank u this makes it feel less scary', 'u got this!!']],
  ['f-fitness', 'discussion', 'how many steps do u guys do a day', 'trying to get 10k but its hard with school', [
    '8k on a good day', 'walking pad under my desk changed everything', 'anything above 7k is great tbh', 'i walk to school instead of the bus now', 'podcasts make walks go by so fast', '10k is kind of an arbitrary number anyway']],
  ['f-body', 'discussion', 'body measurements vs scale', 'stopped weighing myself and started tracking measurements and progress pics. my mental health is so much better', [
    'this is the way', 'scale can go up when u build muscle anyway', 'progress pics are the best tracker', 'same, the scale was messing with my head', 'how often do u measure', 'once a month, same time of day', 'love this mindset']],
  ['f-body', 'question', 'how to improve posture when sitting all day?', 'i study like 8 hours a day and my back is wrecked', [
    'set a timer to get up every 45 mins', 'monitor at eye level', 'feet flat on the floor', 'a cushion for lower back support helps', 'stretch ur hip flexors, they get so tight from sitting', 'thank u i didnt know about the hip flexor thing']],
  ['f-nutrition', 'guide', 'easy high protein breakfasts', 'greek yogurt + berries + granola, eggs on toast, overnight oats with protein powder, cottage cheese bowls. protein at breakfast keeps me full till lunch', [
    'overnight oats before the gym 🫶', 'adding cottage cheese bowls to my list', 'egg muffins are great for meal prep', 'protein pancakes!!', 'i never eat breakfast tbh maybe i should', 'it helped my energy so much', 'saving this']],
  ['f-nutrition', 'question', 'does drinking more water actually help skin', 'everyone says drink water for clear skin but is it real', [
    'it helps if ur dehydrated but its not magic', 'my skin looks less dull when i drink enough', 'its more about sleep and diet tbh', 'i notice it in my under eyes the most', 'cant hurt either way lol', 'true, ill keep at it']],
  ['f-nutrition', 'discussion', 'favourite healthy snacks?', 'trying to snack less on chips', [
    'apple + peanut butter', 'edamame', 'greek yogurt', 'popcorn is lowkey healthy', 'hummus and carrots', 'rice cakes with avocado', 'dark chocolate counts right', 'yes 😌']],
  ['f-face', 'discussion', 'mewing: thoughts?', 'seeing it everywhere. is it legit or nah', [
    'good tongue posture is good for you but dont expect miracles', 'it wont change ur bone structure as an adult', 'it helped me stop mouth breathing at least', 'posture of the whole head and neck matters more', 'ortho is the real answer for jaw stuff', 'fair, ill just focus on posture then']],
  ['f-face', 'question', 'how to make my face look less puffy in the morning', 'i wake up so puffy every day', [
    'less salt at night', 'cold water splash or ice roller', 'sleep with ur head slightly raised', 'gua sha did help me tbh', 'more sleep weirdly makes it better', 'drink water before bed (but not too much lol)', 'ice roller it is']],
  ['f-style', 'discussion', 'building a capsule wardrobe: whats in yours?', 'mine: white tee, black tee, straight jeans, black trousers, trench, blazer, loafers, white trainers. everything goes with everything', [
    'same but navy instead of black since im a summer', 'a good blazer makes everything look put together', 'trench coat is so underrated', 'i need to do this my closet is chaos', 'add a slip skirt!', 'how many pieces total?', 'like 30 including shoes', 'that is so doable']],
  ['f-style', 'question', 'how to dress for my body type?', 'pear shaped and nothing ever fits right', [
    'a line skirts are ur best friend', 'wide leg trousers look amazing on pears', 'tops with details on the shoulders balance it out', 'get things tailored at the waist', 'high waisted everything', 'thank u!! going shopping this weekend']],
  ['f-style', 'discussion', 'perfume recommendations??', 'want something sweet but not too sweet', [
    'cloud by ariana', 'glossier you', 'vanilla girl forever', 'burberry her is so pretty', 'body mists if u want something cheap', 'kayali vanilla 28!!', 'sampling before buying saved me so much money']],
  ['f-questions', 'question', 'where should a total beginner start?', 'i want to glow up but dont know where to start. what made the biggest difference for u', [
    'sleep, spf and water. boring but true', 'posture + moving every day', 'clothes that actually fit you', 'clear skin routine first', 'brows, they frame ur whole face', 'confidence lol (easier said than done)', 'okay starting with sleep and spf this week thank u!!', 'proud of u for starting']],
  ['f-questions', 'question', 'how long did ur glow up take?', 'i feel like im not seeing changes fast enough', [
    'like a year honestly', 'the first 3 months felt like nothing', 'progress pics help u see it', 'its slow then suddenly people notice', 'dont compare ur timeline', 'this made me feel better tysm']],
  ['f-questions', 'question', 'best way to get rid of dark circles?', 'mine are genetic i think', [
    'genetic ones are hard, concealer with peach corrector helps', 'sleep helps a little', 'caffeine eye cream does a tiny bit', 'colour corrector before concealer is the trick', 'embrace them lol i gave up', 'peach corrector it is']],
  ['f-advice', 'serious', 'how do u stop comparing yourself on instagram', 'i always feel worse after scrolling. how do u deal with it', [
    'unfollow anyone who makes u feel bad', 'follow accounts that teach skills instead', 'most pics are edited and filtered', 'compare yourself to you last month', 'screen time limits saved me', 'i deleted the app for a month and felt so much better', 'thank u all this helps a lot 💕']],
  ['f-advice', 'question', 'how do i get more confident talking to people', 'i get so awkward and quiet', [
    'ask people questions about themselves, everyone loves that', 'practice small talk with cashiers lol', 'it gets easier the more u do it', 'remember everyone is thinking about themselves not u', 'eye contact and a smile goes a long way', 'thank u ill try the questions thing']],
  ['f-advice', 'discussion', 'friend keeps commenting on my weight', 'she says it like a joke but it really bothers me', [
    'tell her directly that it bothers u', 'a real friend will stop when u tell them', 'thats not a joke thats rude', 'u deserve better friends tbh', 'maybe she doesnt realise, worth one honest convo', 'update: i told her and she apologised', 'proud of u for speaking up!!']],
  ['f-offtopic', 'discussion', 'what are u listening to rn 🎧', 'drop ur current song', [
    'gym playlist on repeat lol', 'newjeans always', 'old amy winehouse albums', 'sabrina carpenter', 'olivia rodrigo guts', 'lofi while studying', 'taylor obviously', 'chappell roan!!']],
  ['f-offtopic', 'intro', 'introduce yourself here! 👋', 'hii everyone!! say hi below, where ur from and what ur here to work on', [
    'hi! from manchester, here for makeup and skincare', 'hey from melbourne, skincare is my thing', 'amara here, hair care all day', 'berlin, fitness and pilates', 'hi from toronto, brows and lashes 💕', 'hey!! here to learn about style', 'hiii from dublin just vibing', 'welcome everyone!']],
  ['f-offtopic', 'discussion', 'whats everyone watching rn', 'need a new show', [
    'bridgerton', 'the summer i turned pretty', 'gilmore girls rewatch for the 5th time', 'wednesday', 'love island lol', 'normal people if u want to cry', 'gilmore girls is the answer to everything']],
  ['f-offtopic', 'discussion', 'cats or dogs', 'settle this', [
    'cats obviously', 'dogs!!', 'both', 'cats are so underrated', 'dog people are just happier', 'my cat would never forgive me if i said dogs', 'lmao']],
  ['f-offtopic', 'discussion', 'whats ur comfort food', 'mine is mac and cheese', [
    'ramen', 'pasta always', 'my mums soup', 'chocolate chip cookies', 'pizza no question', 'grilled cheese', 'now im hungry']],
  ['f-feedback', 'discussion', 'love the site so far!', 'just wanted to say this place is so nice compared to other forums. keep it up', [
    'agreed!!', 'dark mode is so pretty', 'the vip colours are cute', 'would love a mobile app one day', 'same this is my new favourite forum']],
];
