'use strict';
/* End-to-end acceptance tests: real browser contexts against a real server and PostgreSQL. */
const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const { Client } = require('pg');
const sharp = require('sharp');

const MAIL_DIR = path.join(__dirname, '..', 'storage', 'e2e-mail');
const DB_URL = process.env.DATABASE_URL_E2E || 'postgres://pinkpill:pinkpill@localhost:5432/pinkpill_e2e';
const PASSWORD = 'e2e password 123';

function latestMail(email) {
  const files = fs.existsSync(MAIL_DIR) ? fs.readdirSync(MAIL_DIR).sort() : [];
  for (let i = files.length - 1; i >= 0; i--) {
    const text = fs.readFileSync(path.join(MAIL_DIR, files[i]), 'utf8');
    if (text.startsWith('To: ' + email)) return text;
  }
  return null;
}

async function sql(query, params) {
  const c = new Client({ connectionString: DB_URL });
  await c.connect();
  try { return (await c.query(query, params)).rows; } finally { await c.end(); }
}

/* Navigate to a hash route; reload when already there (a same-hash goto doesn't re-render). */
async function nav(page, hash) {
  if (page.url().endsWith(hash)) await page.reload(); else await page.goto(hash);
  await ready(page);
}

async function ready(page) {
  await page.waitForFunction(() => document.querySelector('#app') && document.querySelector('#app').children.length > 0 && !document.querySelector('#app.is-loading'));
}

/* Register through the UI, then click the emailed verification link. */
async function register(page, username) {
  const email = username.toLowerCase() + '@example.com';
  await nav(page, '/#/register');
  await page.fill('[name=username]', username);
  await page.fill('[name=email]', email);
  await page.fill('[name=password]', PASSWORD);
  await page.fill('[name=birthday]', '1994-06-01');
  await page.check('[name=agree]');
  await page.click('form[data-form=register] button.btn-primary');
  await expect(page.locator('#userbar')).toContainText(username);
  await expect.poll(() => latestMail(email)).not.toBeNull();
  const link = latestMail(email).match(/http:\/\/\S+verify-email\?token=[\w-]+/)[0];
  await page.goto(link); await ready(page);
  await expect(page.locator('h2')).toContainText('Email verified');
}

async function newThread(page, forum, title, content) {
  await nav(page, '/#/post-thread/' + forum);
  await page.fill('[name=title]', title);
  await page.fill('form[data-form=post-thread] textarea[name=content]', content);
  await page.click('form[data-form=post-thread] button.btn-primary');
  await expect(page.locator('h1')).toContainText(title);
  return page.url().match(/threads\/(\d+)/)[1];
}

test.describe.serial('PinkPill acceptance', () => {
  let browser, amy, bea, amyPage, beaPage, threadId;

  test.beforeAll(async ({ browser: b }) => {
    browser = b;
    amy = await browser.newContext(); bea = await browser.newContext();
    amyPage = await amy.newPage(); beaPage = await bea.newPage();
  });
  test.afterAll(async () => { await amy.close(); await bea.close(); });

  test('two separate browsers can create accounts and see each other', async () => {
    await register(amyPage, 'AmyE2E');
    await register(beaPage, 'BeaE2E');
    await nav(beaPage, '/#/members/list');
    await expect(beaPage.locator('.member-list')).toContainText('AmyE2E');
    await beaPage.click('text=AmyE2E'); await ready(beaPage);
    await expect(beaPage.locator('.profile-head h1')).toHaveText('AmyE2E');
  });

  test('they can create threads and reply to each other; posts persist after refresh', async () => {
    threadId = await newThread(amyPage, 'f-skin', 'Retinol purging — how long did yours last?', 'Mine has lasted 5 weeks so far. @BeaE2E any tips?');
    await nav(beaPage, '/#/threads/' + threadId);
    await expect(beaPage.locator('.message-content').first()).toContainText('Mine has lasted 5 weeks');
    await beaPage.fill('form[data-form=reply] textarea', 'Mine stopped around week 6 — hang in there!');
    await beaPage.click('form[data-form=reply] button.btn-primary');
    await expect(beaPage.locator('article.message')).toHaveCount(2);
    await nav(amyPage, '/#/threads/' + threadId);
    await expect(amyPage.locator('article.message').nth(1)).toContainText('week 6');
    await amyPage.reload(); await ready(amyPage);
    await expect(amyPage.locator('article.message')).toHaveCount(2);
    // Amy got a reply alert, Bea got a mention alert — both generated by the server.
    await nav(amyPage, '/#/alerts');
    await expect(amyPage.locator('.alerts-list')).toContainText('BeaE2E replied to the thread');
    await nav(beaPage, '/#/alerts');
    await expect(beaPage.locator('.alerts-list')).toContainText('AmyE2E mentioned you');
  });

  test('reactions, reputation and polls are stored on the server', async () => {
    await nav(beaPage, '/#/threads/' + threadId);
    const first = beaPage.locator('article.message').first();
    await first.locator('.react-wrap > button').click();
    await expect(first.locator('.reactions-bar')).toContainText('You');
    await first.locator('[data-act=rep]').click();
    await beaPage.fill('.modal [name=comment]', 'Helpful!');
    await beaPage.click('.modal button.btn-primary');
    await expect(first.locator('.rep-post')).toContainText('+1 rep');
    // server rejects a second rep for the same post even if the UI is bypassed
    const again = await beaPage.evaluate(async (pid) => {
      const s = await fetch('/api/auth/session').then((r) => r.json());
      return (await fetch('/api/posts/' + pid + '/reputation', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'fetch', 'X-CSRF-Token': s.csrfToken }, body: JSON.stringify({ positive: true }) })).status;
    }, (await first.getAttribute('id')).replace('post-', ''));
    expect(again).toBe(403);
    // poll
    await nav(amyPage, '/#/post-thread/f-makeup');
    await amyPage.fill('[name=title]', 'Cream or powder blush?');
    await amyPage.fill('form[data-form=post-thread] textarea[name=content]', 'Vote below');
    await amyPage.click('.poll-builder summary');
    await amyPage.fill('[name=poll_q]', 'Which do you prefer?');
    await amyPage.locator('[name=poll_opt]').nth(0).fill('Cream');
    await amyPage.locator('[name=poll_opt]').nth(1).fill('Powder');
    await amyPage.click('form[data-form=post-thread] button.btn-primary');
    await expect(amyPage.locator('.poll')).toBeVisible();
    const pollUrl = amyPage.url();
    await beaPage.goto(pollUrl); await ready(beaPage);
    await beaPage.check('input[name=opt] >> nth=0');
    await beaPage.click('form[data-form=poll-vote] button.btn-primary');
    await expect(beaPage.locator('.poll')).toContainText('Total voters: 1');
    await amyPage.reload(); await ready(amyPage);
    await amyPage.click('[data-act=poll-results]');
    await expect(amyPage.locator('.poll')).toContainText('Total voters: 1');
  });

  test('private messages are actually private', async () => {
    await nav(amyPage, '/#/conversations/new?to=BeaE2E');
    await amyPage.fill('[name=title]', 'Secret skincare plan');
    await amyPage.fill('form[data-form=conv-new] textarea', 'Only for you, Bea.');
    await amyPage.click('form[data-form=conv-new] button.btn-primary');
    await expect(amyPage.locator('h1')).toHaveText('Secret skincare plan');
    const url = amyPage.url();
    await beaPage.goto(url); await ready(beaPage);
    await expect(beaPage.locator('.message-content')).toContainText('Only for you');
    // A third member and a guest cannot open it, via the UI or the API.
    const cat = await browser.newContext(); const catPage = await cat.newPage();
    await register(catPage, 'CatE2E');
    await catPage.goto(url); await ready(catPage);
    await expect(catPage.locator('.notice--error')).toContainText('could not be found');
    const convId = url.match(/conversations\/(\d+)/)[1];
    expect(await catPage.evaluate(async (id) => (await fetch('/api/conversations/' + id)).status, convId)).toBe(404);
    const guest = await browser.newContext(); const gp = await guest.newPage();
    await gp.goto('/'); expect(await gp.evaluate(async (id) => (await fetch('/api/conversations/' + id)).status, convId)).toBe(401);
    await cat.close(); await guest.close();
  });

  test('users cannot make themselves admins through browser manipulation', async () => {
    await amyPage.goto('/'); await ready(amyPage);
    const results = await amyPage.evaluate(async () => {
      localStorage.setItem('pinkpill.session', '1');
      localStorage.setItem('pinkpill.db.v1', JSON.stringify({ users: [{ id: '1', role: 'admin' }] }));
      document.cookie = 'role=admin; path=/';
      document.cookie = 'isAdmin=true; path=/';
      // Tamper with the in-memory session the UI uses:
      window.PP.session.user.permissions.push('admin.users', 'admin.settings', 'mod.view_reports', 'mod.ban');
      window.PP.session.user.role = 'super_admin';
      const s = await fetch('/api/auth/session').then((r) => r.json());
      const h = { 'Content-Type': 'application/json', 'X-Requested-With': 'fetch', 'X-CSRF-Token': s.csrfToken, 'X-Role': 'admin' };
      return {
        serverRole: s.user.role,
        promote: (await fetch('/api/admin/users/' + s.user.id + '/role', { method: 'PATCH', headers: h, body: JSON.stringify({ role: 'admin' }) })).status,
        settings: (await fetch('/api/admin/settings', { method: 'PATCH', headers: h, body: JSON.stringify({ site_name: 'pwned' }) })).status,
        reports: (await fetch('/api/mod/reports', { headers: h })).status,
        profileRole: (await fetch('/api/account/profile', { method: 'PATCH', headers: h, body: JSON.stringify({ role: 'admin' }) })).status,
      };
    });
    expect(results).toEqual({ serverRole: 'member', promote: 403, settings: 403, reports: 403, profileRole: 422 });
    // The tampered UI shows the admin tab list, but every panel fails with the server's 403.
    await nav(amyPage, '/#/mod/reports');
    await expect(amyPage.locator('.notice--error')).toContainText('permission');
    // A fresh page load restores the real (member) session from the server.
    await amyPage.reload(); await ready(amyPage);
    await expect(amyPage.locator('#userbar a[href="#/mod"]')).toHaveCount(0);
  });

  test('moderation is server-enforced: a moderator bans a member, who can then no longer post', async () => {
    await sql("UPDATE users SET role_id = 'moderator' WHERE username = 'BeaE2E'");
    await beaPage.reload(); await ready(beaPage);
    // Report → moderator queue
    await nav(amyPage, '/#/threads/' + threadId);
    await amyPage.locator('article.message').nth(1).locator('[data-act=report]').click();
    await amyPage.selectOption('.modal select[name=preset]', 'Spam or bots');
    await amyPage.click('.modal button.btn-primary');
    await nav(beaPage, '/#/mod/reports');
    await expect(beaPage.locator('.report-row').first()).toContainText('Spam');
    await beaPage.locator('[data-act=resolve-report]').first().click();
    await expect(beaPage.locator('.empty')).toContainText('No open reports');
    // Ban Amy from her profile
    const amyId = (await sql("SELECT id FROM users WHERE username = 'AmyE2E'"))[0].id;
    await nav(beaPage, '/#/members/' + amyId);
    await beaPage.click('[data-menu=profile-more]');
    await beaPage.click('[data-act=ban]');
    await beaPage.fill('.modal [name=reason]', 'E2E test ban');
    await beaPage.click('.modal button.btn-danger');
    await expect(beaPage.locator('.profile-head')).toContainText('Banned');
    // Amy can read but cannot reply.
    await nav(amyPage, '/#/threads/' + threadId);
    await expect(amyPage.locator('form[data-form=reply]')).toHaveCount(0);
    const status = await amyPage.evaluate(async (id) => {
      const s = await fetch('/api/auth/session').then((r) => r.json());
      return (await fetch('/api/threads/' + id + '/posts', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'fetch', 'X-CSRF-Token': s.csrfToken }, body: JSON.stringify({ content: 'sneaky' }) })).status;
    }, threadId);
    expect(status).toBe(403);
    // The ban and the report resolution are in the moderation log.
    await nav(beaPage, '/#/mod/log');
    await expect(beaPage.locator('table')).toContainText('user.ban');
    await expect(beaPage.locator('table')).toContainText('report.resolved');
    await nav(beaPage, '/#/members/' + amyId);
    await beaPage.click('[data-menu=profile-more]');
    await beaPage.click('[data-act=ban]');
    await expect(beaPage.locator('.profile-head')).not.toContainText('Banned');
  });

  test('images are uploaded to the server, not localStorage', async () => {
    const png = await sharp({ create: { width: 300, height: 300, channels: 3, background: '#f472b6' } }).png().toBuffer();
    const file = path.join(__dirname, '..', 'storage', 'e2e-avatar.png');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, png);
    await nav(beaPage, '/#/account/personal');
    await beaPage.setInputFiles('input[name=avatar_file]', file);
    await beaPage.click('form[data-form=account-personal] button.btn-primary');
    const img = beaPage.locator('.avatar-editor img');
    await expect(img).toHaveAttribute('src', /^\/media\/[0-9a-f-]{36}$/);
    const res = await beaPage.request.get(await img.getAttribute('src'));
    expect(res.headers()['content-type']).toBe('image/webp');
    const stored = await beaPage.evaluate(() => JSON.stringify(localStorage).length);
    expect(stored).toBeLessThan(5000);
  });

  test('search works against the database', async () => {
    await nav(beaPage, '/#/search?q=' + encodeURIComponent('retinol purging'));
    await expect(beaPage.locator('.activity-item').first()).toContainText('Retinol purging');
  });

  test('data persists after restarting the server', async () => {
    const port = 3201;
    const start = () => new Promise((resolve, reject) => {
      const p = spawn(process.execPath, [path.join(__dirname, 'server.js')], { env: Object.assign({}, process.env, { E2E_PORT: String(port), E2E_KEEP_DB: '1' }), stdio: ['ignore', 'pipe', 'pipe'] });
      p.stdout.on('data', (d) => { if (/listening/.test(String(d))) resolve(p); });
      p.stderr.on('data', (d) => process.stderr.write(d));
      p.on('exit', (code) => reject(new Error('server exited ' + code)));
    });
    let server = await start();
    const before = await (await fetch(`http://localhost:${port}/api/threads/${threadId}`)).json();
    expect(before.posts.length).toBe(2);
    server.kill('SIGTERM');
    await new Promise((r) => server.on('exit', r));
    server = await start();
    const after = await (await fetch(`http://localhost:${port}/api/threads/${threadId}`)).json();
    expect(after.thread.title).toBe(before.thread.title);
    expect(after.posts.map((p) => p.content)).toEqual(before.posts.map((p) => p.content));
    server.kill('SIGTERM');
  });
});
